version: '3.8'

services:
  voting-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: local-voting-app
    ports:
      - "3000:3000"
    volumes:
      # Persist database data with proper permissions
      - voting-data:/app/backend/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASS=${ADMIN_PASS:-admin123}
      - SESSION_SECRET=${SESSION_SECRET:-voting-app-secret-change-in-production}
    restart: unless-stopped
    networks:
      - voting-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  voting-network:
    driver: bridge

volumes:
  voting-data:
    driver: local
